### PR TITLE
test

### PR DESCRIPTION
**Pull request by mikhail-klimko**
## What

Ignore. Checking CI

### CODE REVIEW

**Comment by mikhail-klimko** [comment]
test

**Comment by mikhail-klimko** [comment]
test

**Comment by korenyoni** [comment]
Closing — worked with @mikhail-klimko to test the `/test` CI trigger (see: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Pull request closed without merging**
