### PR TITLE
Chore: Documentation Overhaul, General Cleanup

### PR DESCRIPTION
**Pull request by korenyoni**
## What

* Port all documentation to be generated via [terraform-plugin-docs](https://github.com/hashicorp/terraform-plugin-docs)
* Add https://allcontributors.org
* Add issue templates.
* Misc cleanups
* Update to go 1.18

## Why

* Documentation is missing

CleanShot 2023-03-05 at 19 59 16@2x

## PR Checklist

* [x] _I have [allowed changes to my fork to be made](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)._
* [x] _I have added tests, assuming new tests are warranted_.
* [x] _I have updated the Terraform docs in this repo, assuming any changes to the schema of Resources or Data Sources have been made._
* [x] _I understand that the `/test` comment will be ignored by the CI trigger [unless it is made by a repo admin or collaborator](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/#support-for-building-pull-requests-from-forks)._

### CODE REVIEW

**Review by bathenyosefov — APPROVED** [review]

**Comment by korenyoni** [comment]
@all-contributors bot

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code, doc, tests

**Comment by korenyoni** [comment]
@all-contributors bot

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code, doc and tests

**Comment by korenyoni** [comment]
https://github.com/all-contributors please add @korenyoni for code

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code, tests and doc

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code, tests, doc

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code, tests, doc

**Comment by korenyoni** [comment]
@all-contributors please add @korenyoni for code, tests, doc

**Pull request merged**
