### PR TITLE
Feat: Data source project

### LINKED ISSUE #116: [Feature]: Project Data Source
### What would you like to be added?

Currently no data source for project and the project resource outputs aren't documented?

It would be good to have a data resource for a project to perform validation before attempting to attach a pipeline to a project that may not exist.

### PR DESCRIPTION
**Pull request by Jake-Mok-Nelson**
## What

Create a project data resource for the Terraform Codefresh provider

Fixes #116 

## Why

A project data resource would allow us to perform validation before allowing a pipeline to target a project that may or may not exist. Ordinarily you'd just target the project resource but pipelines are not always created in the same location as the projects.

## Notes

I have no ability to test this at the moment (I do not have connectivity to a Codefresh system), I'm hoping you can validate that it's good.

## Checklist

* [x] _I have read [CONTRIBUTING.md](https://github.com/codefresh-io/terraform-provider-codefresh/blob/master/README.md)._
* [x] _I have [allowed changes to my fork to be made](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)._
* [ ] _I have added tests, assuming new tests are warranted_.
* [x] _I understand that the `/test` comment will be ignored by the CI trigger [unless it is made by a repo admin or collaborator](https://codefresh.io/docs/docs/pipelines/triggers/git-triggers/#support-for-building-pull-requests-from-forks)._

### CODE REVIEW

**Comment by korenyoni** [comment]
Sorry for the delay and thanks for the contribution.

I will have to take over the branch, add some tests and also run `make docs`. I will see if I can get to it next week.

**Comment by ilia-medvedev-codefresh** [comment]
@Jake-Mok-Nelson I will be taking over this PR, will try to get it merged this week. Pushed some changes to your branch (merged from our upstream and added docs)

**Review by ilia-medvedev-codefresh — APPROVED** [review]

**Pull request merged**
